---
# Unattended upgrades default variables

# Enable or disable unattended upgrades
auto_updates: true

# Automatic reboot settings
unattended_upgrades_automatic_reboot: true
unattended_upgrades_automatic_reboot_time: "03:00"

# Package removal settings
unattended_upgrades_remove_unused_kernel_packages: true
unattended_upgrades_remove_new_unused_dependencies: true
unattended_upgrades_remove_unused_dependencies: true

# Upgrade behavior
unattended_upgrades_autofix_interrupted_dpkg: true
unattended_upgrades_minimal_steps: true

# Origins to allow upgrades from
unattended_upgrades_origins_patterns:
  - '${distro_id}:${distro_codename}'
  - '${distro_id}:${distro_codename}-security'
  - '${distro_id}ESMApps:${distro_codename}-apps-security'
  - '${distro_id}ESM:${distro_codename}-infra-security'
